[tox]
minversion = 4.32.0
skip_missing_interpreters = true
envlist =
    py{310,311,312}-django42-wagtail{63,70,72,73}-factoryboy32
    py{310,311,312,313}-django52-wagtail{63,70,72,73}-factoryboy33
    py314-django{52,60}-wagtail73-factoryboy33

    coverage-report
    lint

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
commands = coverage run --parallel -m pytest {posargs}
extras = test
deps =
    django42: django>=4.2,<5.0
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
    wagtail63: wagtail>=6.3,<6.4
    wagtail70: wagtail>=7.0,<7.1
    wagtail72: wagtail>=7.2,<7.3
    wagtail73: wagtail>=7.3,<7.4
    factoryboy32: factory-boy>=3.2,<3.3
    factoryboy33: factory-boy>=3.3,<3.4

[testenv:coverage-report]
basepython = python3.13
deps = coverage
pip_pre = true
skip_install = true
commands =
    coverage combine
    coverage report

[testenv:lint]
basepython = python3.13
deps = flake8
commands =
    ruff format --check .
    ruff check .
